---
title: "ENV 730"
subtitle: "Environmental Data Science in R: Introduction to Data Integration and Machine Learning"
---

## Meeting Information

Th 2:30pm-5:20pm in Kroon 319

## Instructor

Dr. Sparkle L. Malone

sparkle.malone\@yale.edu

Office Hours: Mondays 12pm-3pm

Teaching Fellow: TBD

## Limited Enrollment

<b>Prerequisites:</b>

-   [R Series Training](https://research.computing.yale.edu/training/r-series)

## Format

The primary format is synchronous, in-person lectures, discussions, and workshops.

<b>Course Description:</b> In today's world, understanding environmental data and making informed decisions based on it is crucial for addressing complex environmental challenges. This course serves as an introductory exploration into the integration of environmental data using R programming language, coupled with machine learning techniques. Participants will gain hands-on experience in handling, analyzing, and interpreting environmental datasets, with a focus on leveraging the power of R for data integration and predictive modeling.

## Learning Objectives

1.  We will use coding and reproducible best practices.
2.  We will become familiar with different types of environmental data.
3.  We will use machine learning to explore adaptive management solutions.

## Required Materials

-   [R for Data Science](https://r4ds.had.co.nz/index.html)
-   [R For Earth System](https://pjbartlein.github.io/REarthSysSci/index.html)
-   [Spatial Data Science with R and "terra"](https://rspatial.org/index.html)

<b>Computing needs:</b> Please bring a laptop to class. Your laptop must have both [R](https://cloud.r-project.org/) and [Rstudio](https://www.rstudio.com/products/rstudio/download/) installed and operational prior to the start of this course. Ideally you will have 16GB of RAM or higher, dual Core 2Ghz or higher (Intel Core i5 processor or equivalent) and your operating system should be Windows 10 or higher or OS X 10.14 or higher.

## Course Policies

<b>Attendance Policy:</b> Regular in-person classroom attendance is required of all students. When extenuating circumstances require accommodation, Dr. Malone will arrange for remote attendance via zoom.

<b>Late Policy:</b> All assignments submitted after the due date are subject to a late penalty. For the first 24 hour period beyond an assignment's due date there is a 10% penalty, which increases by 10% for each additional 24 hour period.

[Academic integrity](http://catalog.yale.edu/undergraduate-regulations/regulations/academic-dishonesty/) is a core university value that ensures respect for the academic reputation of the University, its students, faculty and staff, and the degrees it confers. The University expects that students will conduct themselves in an honest and ethical manner and respect the intellectual work of others. Please ask about my expectations regarding permissible or encouraged forms of student collaboration if they are unclear. Any work that you submit at any stage of the writing process—thesis, outline, draft, bibliography, final submission, presentations, blog posts, and more—must be your own; you also may not use material generated by ChatGPT or any other AI writing software. In addition, any words, ideas, or data that you borrow from other people and include in your work must be properly documented. Failure to do either of these things is plagiarism. <i>-Poorvu Center</i>

Before collaborating with an AI chatbot on your work for this course, please request permission by sending me a note that describes (a) how you intend to use the tool and (b) how using it will enhance your learning. Any use of AI to complete an assignment must be acknowledged in a citation that includes the prompt you submitted to the bot, the date of access, and the URL of the program. <i>-Poorvu Center</i>

<b>Diversity and Disability Statement:</b> Our institution values diversity and inclusion; we are committed to a climate of mutual respect and full participation. Our goal is to create learning environments that are usable, equitable, inclusive and welcoming. If there are aspects of the instruction or design of this course that result in barriers to your inclusion or accurate assessment or achievement, please notify Dr. Malone as soon as possible. Disabled students are also welcome to contact Student Accessibility ServicesLinks to an external site. to discuss a range of options to removing barriers in the course, including accommodations. <i>-Poorvu Center</i>

<b>Usability, Disability and Design:</b> I am committed to creating a course that is inclusive in its design. If you encounter barriers, please let me know immediately so that we can determine if there is a design adjustment that can be made or if an accommodation might be needed to overcome the limitations of the design. I will consider creative solutions, as long as they do not compromise the intent of the assessment or learning activity. You are also welcome to contact Student Accessibility ServicesLinks to an external site. to begin this conversation or to establish accommodations for this or other courses. I welcome feedback that will assist me in improving the usability and experience for all students. <i>-Poorvu Center</i>

## Assignments, Assessments & Grading

-   Exam (125 points): This exam is designed to evaluate basic knowledge of R and Rstudio. A score of 90% or higher signifies that students have a strong foundational knowledge of R and R studio and are prepared to focus on the content in this course.
-   Attendance: Regular in-person classroom attendance is required of all students. When extenuating circumstances require accommodation, Dr. Malone will arrange for remote attendance via zoom.
-   Post-workshop Assessments (\~150 points): Assessments are assignments that require direct application of tools and analysis approaches.
-   Major Assessments (200 points): Activities designed to test mastery of concepts.
-   Final Project (200 points):
    -   Proposal Presentation (50 points)
    -   Final Report (100 points)
    -   Final Project Presentation (50 points)

## Course Ouline:

+-------------+-------------------------------------------------------------+
| ~Week       | Workshop Topic                                              |
+=============+=============================================================+
| 1-6         | **Introduction to R**                                       |
|             |                                                             |
|             | -   Open Science Best Practices                             |
|             |                                                             |
|             | -   Data Basics (Importing, visualizing, manipulating data) |
|             |                                                             |
|             | -   Vector Data Manipulation & Visualization (sf)           |
|             |                                                             |
|             | -   Raster Data Manipulation & Visualization (terra)        |
+-------------+-------------------------------------------------------------+
| 7-8         | **Data Integration in R**                                   |
|             |                                                             |
|             | -   Techniques for Data Integration                         |
+-------------+-------------------------------------------------------------+
| 9-10        | **Machine Learning in R**                                   |
|             |                                                             |
|             | -   RandomForest Model Development: Fitting models          |
|             |                                                             |
|             | -   RandomForest Model Development: Validating models       |
|             |                                                             |
|             | -   RandomForest Model Development: Sensitivity Analysis    |
+-------------+-------------------------------------------------------------+
| 11-12       | **Dynamic Models in R**                                     |
|             |                                                             |
|             | -   Spatial Model Visualization                             |
|             |                                                             |
|             | -   Model Competition                                       |
+-------------+-------------------------------------------------------------+
| 13-16       | **Final Project (Independent)**                             |
|             |                                                             |
|             | -   Proposal Presentation                                   |
|             |                                                             |
|             | -   Final Report                                            |
|             |                                                             |
|             | -   Final Project Presentation                              |
+-------------+-------------------------------------------------------------+
